# Generated by Django 6.0.2 on 2026-03-01 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionEmailWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='uniq_vote_per_position_per_election',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='bio_short',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='access_mode',
            field=models.CharField(choices=[('code_only', 'Code only (Name + Code)'), ('whitelist_email', 'Protected (Email whitelist + OTP)'), ('any_email_domain', 'Open (Allowed domains + OTP)'), ('any_email', 'Open (Any email + OTP)')], default='code_only', max_length=30),
        ),
        migrations.AddField(
            model_name='election',
            name='allowed_email_domains',
            field=models.CharField(blank=True, help_text='Comma-separated domains e.g. gmail.com,yahoo.com', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='require_email_otp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.voter'),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.voter'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('voter__isnull', False)), fields=('voter', 'election', 'position'), name='uniq_vote_code_voter'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('voter_email__isnull', False)), fields=('voter_email', 'election', 'position'), name='uniq_vote_email_voter'),
        ),
        migrations.AddField(
            model_name='electionemailwhitelist',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_whitelist', to='app.election'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='app.election'),
        ),
        migrations.AddConstraint(
            model_name='electionemailwhitelist',
            constraint=models.UniqueConstraint(fields=('election', 'email'), name='uniq_email_whitelist'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['election', 'email'], name='app_emailot_electio_89fcf5_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['expires_at'], name='app_emailot_expires_0c31cf_idx'),
        ),
    ]
